version: '3'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    tty: true
  db:
    image: mysql:8.0.30
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysqldb:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

volumes:
  mysqldb:
    driver: local
  bundle:
    driver: local
